export const FORM_PATCH_SUCCESS = "FORM/PATCH_SUCCESS"
export const FORM_PATCH_ERROR = "FORM/PATCH_ERROR"
export const FORM_POST_SUCCESS = "FORM/POST_SUCCESS"
export const FORM_POST_ERROR = "FORM/POST_ERROR"
export const FORM_POST_PROCESSING = "FORM/POST_PROCESSING"
export const FORM_PATCH_PROCESSING = "FORM/PATCH_PROCESSING"

