export const SAVE_ITEM = "DETAILED_CARD/SAVE_ITEM"
export const FETCH_ITEM = "DETAILED_CARD/FETCH_ITEM"
export const FETCH_ERROR = "DETAILED_CARD/FETCH_ERROR"
export const FETCH_SUCCESS = "DETAILED_CARD/FETCH_SUCCESS"