export const DETAILED_CARD_SAVE_ITEM = "DETAILED_CARD/SAVE_ITEM"
export const DETAILED_CARD_FETCH_ERROR = "DETAILED_CARD/FETCH_ERROR"
export const DETAILED_CARD_FETCH_SUCCESS = "DETAILED_CARD/FETCH_SUCCESS"
export const DETAILED_CARD_FETCH = "DETAILED_CARD/FETCH"