export const CART_REMOVE = "CART/REMOVE_DUPLICATE"
export const CART_CLEAR_CART = "CART/CLEAR_CART"
export const CART_SAVE_SUCCESS = "CART/SAVE_SUCCESS"
export const CART_SAVE_ERROR = "CART/SAVE_ERROR"
export const CART_SAVE_ORDER = "CART/SAVE_ORDER"
export const CART_BUY_ITEM = "CART/BUY_ITEM"
export const ADD_TO_CART = "CART/ADD_TO_CART"
export const CART_REMOVE_QUANTITY = "CART/REMOVE_QUANTITY"
export const CART_SET_QUANTITY = "CART/SET_QUANTITY"


