export const CART_ADD_ITEM = "CART/ADD_ITEM"
export const CART_REMOVE = "CART/REMOVE_DUPLICATE"
export const CART_CLEAR_CART = "CART/CLEAR_CART"
export const CART_SAVE_SUCCESS = "CART/SAVE_SUCCESS"
export const CART_SAVE_ERROR = "CART/SAVE_ERROR"
export const CART_SAVE_ORDER = "CART/SAVE_ORDER"
export const CART_BUY_ITEM = "CART/BUY_ITEM"
export const CART_ITEM_QUANTITY = "CART/ITEM_QUANTITY"

