export const SAVE_ORDER = "DETAILED_ORDER/SAVE_ITEM"
export const FETCH_ORDER = "DETAILED_ORDER/FETCH_ITEM"
export const FETCH_ERROR = "DETAILED_ORDER/FETCH_ERROR"
export const FETCH_SUCCESS = "DETAILED_ORDER/FETCH_SUCCESS"