export const DETAILED_ORDER_SAVE_ORDER = "DETAILED_ORDER/SAVE_ITEM"
export const DETAILED_ORDER_FETCH_ERROR = "DETAILED_ORDER/FETCH_ERROR"
export const DETAILED_ORDER_FETCH_SUCCESS = "DETAILED_ORDER/FETCH_SUCCESS"
export const DETAILED_ORDER_FETCH = "DETAILED_ORDER/FETCH"