export const ORDERS_SAVE_ORDERS = "ORDERS/SAVE_ORDERS"
export const ORDERS_FETCH_SUCCESS = "ORDERS/FETCH_SUCCESS"
export const ORDERS_FETCH_ERROR = "ORDERS/FETCH_ERROR"
export const ORDERS_FETCH_ORDERS = "ORDERS/FETCH_ORDERS"
